name: businessOxygen
favicon: null
layout_spectrum: 0.3169641534332186
typography_spectrum: 0.7158064851537347
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.7273525479249656
  lightness: 0.25676347268745303
  saturation: 0.16415271605364978
  rhythmicContrast: 0.9615312658715993
purpose: []
